[workspace]
name = "igrafx-knime-extension"
version = "1.4.0"
authors = ["iGrafx <support@igrafx.com>"]
description = "iGrafx Mining Knime Extension."
license = "MIT"
license-file = "LICENSE.TXT"
readme = "README.md"
repository = "https://github.com/igrafx/KNIME-Mining-connector"
channels = ["knime", "conda-forge", "https://repo.anaconda.com/pkgs/main", "https://repo.anaconda.com/pkgs/r"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
test = { cmd = "pytest" }
format = { cmd = "ruff format ." }

# ======================
# Platform-specific conda dependencies
# ======================

[target.win-64.dependencies]
python = ">=3.10.0, <3.12.1"
urllib3 = "2.2.1.*"
requests = "2.31.0.*"
ca-certificates = "2024.2.2.*"
libflang = "5.0.0.*"
ucrt = "10.0.22621.0.*"
networkx= ">=3.0.0, <3.3.0"


[target.linux-64.dependencies]
aws-c-auth = "0.7.4.*"
aws-c-cal = "0.6.2.*"
aws-c-common = "0.9.3.*"
aws-c-compression = "0.2.17.*"
aws-c-event-stream = "0.3.2.*"
aws-c-http = "0.7.13.*"
aws-c-io = "0.13.32.*"
aws-c-mqtt = "0.9.6.*"
aws-c-s3 = "0.3.17.*"
aws-c-sdkutils = "0.1.12.*"
aws-checksums = "0.1.17.*"
aws-crt-cpp = "0.23.1.*"
aws-sdk-cpp = "1.11.156.*"
ca-certificates = "2023.11.17.*"
urllib3 = "2.2.1.*"
requests = "2.31.0.*"
networkx= ">=3.0.0, <3.3.0"

[target.osx-64.dependencies]
aws-c-auth = "0.7.4.*"
aws-c-cal = "0.6.2.*"
aws-c-common = "0.9.3.*"
aws-c-compression = "0.2.17.*"
aws-c-event-stream = "0.3.2.*"
aws-c-http = "0.7.13.*"
aws-c-io = "0.13.32.*"
aws-c-mqtt = "0.9.6.*"
aws-c-s3 = "0.3.17.*"
aws-c-sdkutils = "0.1.12.*"
aws-checksums = "0.1.17.*"
aws-crt-cpp = "0.23.1.*"
aws-sdk-cpp = "1.11.156.*"
ca-certificates = "2023.11.17.*"
libcxx = ">=18"
urllib3 = "2.2.1.*"
requests = "2.31.0.*"
networkx= ">=3.0.0, <3.3.0"

[target.osx-arm64.dependencies]
python = ">=3.10.0, <3.12.1"
urllib3 = "2.2.1.*"
requests = "2.31.0.*"
networkx= ">=3.0.0, <3.3.0"

[pypi-dependencies]
certifi = ">=2023.11.17,<2026.0.0"
charset-normalizer = ">=3.3.2,<4.0.0"
greenlet = ">=3.0.3,<4.0.0"
idna = ">=3.7,<4.0"
igrafx-mining-sdk = ">=2.36.1,<3.0.0"
networkx = ">=3.2.1,<4.0.0"
python-dotenv = ">=1.0.1,<2.0.0"
sqlalchemy = ">=2.0.29,<3.0.0"
toml = ">=0.10.2,<1.0.0"
typing-extensions = ">=4.11.0,<5.0.0"

[target.unix.dependencies]
pixi-pycharm = "*"

[feature.build.dependencies]
python = ">=3.10.0, <3.12.1"
knime-extension-bundling = "5.5.*"

[feature.build.tasks]
build = { args = [{ "arg" = "dest", "default" = "./local-update-site" }], cmd = "python ./.pixi/envs/build/bin/build_python_extension.py . {{ dest }}" }

[environments]
build = {features = ["build"], no-default-feature = true}

[dependencies]
python = ">=3.10.0, <3.12.1"
knime-extension-bundling = "5.5.0.*"
knime-extension = "*"
knime-python-base = "*"
pixi-pycharm = ">=0.0.8,<0.0.9"
py4j = ">=0.10.9.9,<0.11"
pydruid = "0.6.6.*"


